receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317

exporters:
  prometheus:
    endpoint: localhost:8889
    const_labels:
      label1: value1
  logging:

  otlp:
    endpoint: jaeger-all-in-one:14250
    tls:
      insecure: true

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
